version: '3.8'
services:
  nginx:
    container_name: nginx
    build: requirements/nginx/
    image: nginx:42
    restart: always
    depends_on:
      - wordpress
      - adminer
    ports:
      - "443:443"
    networks:
      - mynetwork
    volumes:
      - WordPress:/var/www/html
    stdin_open: true
    tty: true

  wordpress:
    container_name: wordpress
    build: requirements/wordpress/
    image: wordpress:42
    restart: always
    depends_on:
      - mariadb
    networks:
      - mynetwork
    volumes:
     - WordPress:/var/www/html
    env_file: .env
    stdin_open: true
    tty: true
  
  mariadb:
    container_name: mariadb
    build: requirements/mariadb/
    image: mariadb:42
    restart: always
    networks:
      - mynetwork
    volumes:
      - db:/var/lib/mysql
    env_file: .env
  
  #BONUS 
  adminer:
    container_name: adminer
    build: requirements/adminer/
    image: adminer:42
    restart: always
    networks:
      - mynetwork
    env_file: .env
  
  redis:
    container_name: redis
    build: requirements/redis/
    image: redis:42
    restart: always
    networks:
      - mynetwork
    env_file: .env
  
  static-web:
    container_name: static-web
    build: requirements/static-web/
    image: static-web:42
    volumes:
     - WordPress:/var/www/html
    networks:
      - mynetwork
    stdin_open: true
    tty: true

  ftp:
    container_name: ftp
    build: requirements/ftp/
    image: ftp:42
    restart: always
    volumes:
      - WordPress:/var/www/html
    networks:
      - mynetwork
    ports:
      - "21:21"
      - "20:20"
      - "40000-40050:40000-40050"
    env_file: .env
    stdin_open: true
    tty: true

  cadvisor:
    container_name: cadvisor
    build: requirements/cadvisor/
    image: cadvisor:42
    ports:
      - "8080:8080"
    networks:
      - mynetwork
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro 
      - /sys:/sys:ro 
      - /var/lib/docker/:/var/lib/docker:ro
    restart: always


# NETWORK
networks:
  mynetwork:
    name : mynetwork
    driver : bridge

# VOLUME
volumes:
  db:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aaudevar/data/db

  WordPress:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: /home/aaudevar/data/wordpress
